env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install twine
        run: pip3 install twine
      - name: Publish to PyPI
        run: make upload
name: Publish
on:
  push:
    tags: [v*]
  workflow_dispatch:
